[project]
name = "ticket-optimizer_Lombardy"
version = "0.1.0"
description = "A tool to save on transport tickets."
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "mip>=1.15.0",
]

[tool.basedpyright]
pythonVersion = "3.12"
